name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

env:
  PLUGIN_NAME: commentator

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  build:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Build plugin
        env:
          TAG_NAME: ${{ needs.release-please.outputs.tag_name }}
        run: |
          cd ./src/editor/base/parser
          bun i --force
          bun run build
          cd ../../../..
          bun i --force
          bun run build
          mkdir ${{ env.PLUGIN_NAME }}
          cp main.js manifest.json styles.css ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}-${TAG_NAME}.zip ${{ env.PLUGIN_NAME }}
          ls

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ needs.release-please.outputs.tag_name }} \
            main.js \
            manifest.json \
            styles.css \
            ${{ env.PLUGIN_NAME }}-${{ needs.release-please.outputs.tag_name }}.zip \
            --clobber
